apiVersion: v1
kind: Namespace
metadata:
  name: secureshop
  labels:
    app.kubernetes.io/part-of: secureshop
    pod-security.kubernetes.io/enforce: restricted   # US-034: enforce hardened pod security
